#ifndef __ERROR_MSG_H__
#define __ERROR_MSG_H__

#include "header.h"
typedef enum ErrorMsgKind
{
    SYMBOL_UNDECLARED,
    SYMBOL_IS_NOT_TYPE,
    SYMBOL_REDECLARED,
    NOT_FUNCTION_NAME,
    ARRAY_SIZE_NOT_INT,
    ARRAY_SIZE_NEGATIVE,
    ARRAY_SUBSCRIPT_NOT_INT,
    NOT_ASSIGNABLE,
    NOT_REFERABLE,
    INCOMPATIBLE_ARRAY_DIMENSION_DECL_GT_REF,
    INCOMPATIBLE_ARRAY_DIMENSION_DECL_LT_REF,
    TRY_TO_INIT_ARRAY,
    ASSIGN_NON_CONST_TO_GLOBAL,
    TOO_FEW_ARGUMENT,
    TOO_MANY_ARGUMENT,
    PASS_SCALAR_TO_ARRAY,
    PASS_ARRAY_TO_SCALAR,
    PARAMETER_TYPE_UNMATCH,
    RETURN_TYPE_UNMATCH,
    RETURN_ARRAY
} ErrorMsgKind;
void printErrorMsg(AST_NODE* node, char* str, ErrorMsgKind errorMsgKind);

#endif